export const GEOLOCATION_DATA_DID_LOAD = 'GEOLOCATION_DATA_DID_LOAD'
export const GALLERY_LOCATION_CHANGED = 'GALLERY_LOCATION_CHANGED'
export const INIT_GALLERY_SERVICES = 'INIT_GALLERY_SERVICES'
export const REQUEST_ART_DETAIL = 'REQUEST_ART_DETAIL'
export const RECEIVE_ART_DETAIL = 'RECEIVE_ART_DETAIL'
export const RECEIVE_ART_LIST = 'RECEIVE_ART_LIST'
export const STOP_LOADER = 'STOP_LOADER'
export const UPDATE_ART_LIST = 'UPDATE_ART_LIST'

// Song List
export const ADD_SONG = 'ADD_SONG'
export const PLAY_SONG = 'PLAY_SONG'
export const LIKE_SONG = 'LIKE_SONG'


// Profile
export const REQUEST_POPULAR_GENRES = 'REQUEST_POPULAR_GENRES'
export const RECEIVE_POPULAR_GENRES = 'RECEIVE_POPULAR_GENRES'
export const TOGGLE_USER_PREFERRED_GENRE = 'TOGGLE_USER_PREFERRED_GENRE'