
export const INIT_GALLERY_SERVICES = 'INIT_GALLERY_SERVICES'
export const GEOLOCATION_DATA_DID_LOAD = 'GEOLOCATION_DATA_DID_LOAD'
export const GALLERY_LOCATION_CHANGED = 'GALLERY_LOCATION_CHANGED'
export const UPDATE_CURRENT_GALLERY = 'UPDATE_CURRENT_GALLERY'
