export const GEOLOCATION_DATA_DID_LOAD = 'GEOLOCATION_DATA_DID_LOAD'
export const GALLERY_LOCATION_CHANGED = 'GALLERY_LOCATION_CHANGED'
export const INIT_GALLERY_SERVICES = 'INIT_GALLERY_SERVICES'
export const LOAD_ART_DETAIL = 'LOAD_ART_DETAIL'
export const RECEIVE_GALLERY_ART = 'RECEIVE_GALLERY_ART'
export const STOP_LOADER = 'STOP_LOADER'
export const UPDATE_CURRENT_GALLERY = 'UPDATE_CURRENT_GALLERY'

export const API_ERROR = 'API_ERROR'
